### ISSUE TITLE
Some CPAN testers reports for your consideration

### ISSUE THREAD

**Issue by Mekk** [TLINDEN/Crypt--PWSafe3#8]
I got those for Passwd::Keyring::PwSafe3 but they seem to be caused by your module. Not sure whether they are sufficient to diagnose but mayhaps…

1) Windows problems with temporary file (both practically identical)

http://www.cpantesters.org/cpan/report/c6375bfe-6c15-1014-b28c-64d78ddf5304
http://www.cpantesters.org/cpan/report/3df707a4-6bfe-1014-8823-09d9f6238fb6

(before going deeper: I'd consider using File::Temp instead of your current  method, mayhaps the name turns too long, or there is some collision)

2) Integrity failure

http://www.cpantesters.org/cpan/report/0df0824a-9721-11e4-b221-9e126cbd7f71

(this is quite ugly, looks like first save crashed but later on things worked properly)

**Comment by TLINDEN** [comment]
Hi,

the links aren't working ("The page isn't redirecting properly").


- Tom

**Comment by Mekk** [comment]
cpantesters seems to be down just now (www.cpantesters.org is also not available at the moment), I hope it is something temporary and we simply need to wait.

In the meantime, as far as I remember:
- „Windows” errors were reporting „No such file or directory C:\TEMP\.vault-...restoftheratherlongname”
- „mysterious” error reported integrity failure on first save without much detail (and it was interesting that further saves worked OK, mayhaps again sth related to preserving those extra fields my example base has inside?)

**Comment by Mekk** [comment]
(in the former case, as I said, I would recommend switching to File::Temp for temporary file management, whatever the problem is, this module is likely to try best; in the latter I mostly ask whether you know about any reasons worth checking, or diagnostics which could be enabled to get more info next time)

**Comment by TLINDEN** [comment]
Ok, I switched to File::Temp. This should fix both issues. In the "mysterious" case: the module saves files in the following way: 
1) write everything to a tmpfile
2) within an eval{} re-open that file and look if it validates
3) if ok, move the tmpfile to the specified location
4) if not ok, keep the original file, if present, untouched and croak

The latter is, what happend in the "mysterious" case, since writing the tmpfile failed in some way, re-opening it, seems to fail as well. So, hopefully, now that I use File::Temp, this should be fixed as well.

**Comment by Mekk** [comment]
Thank you. I will let you know in case problem reappears, so far I think the issue can be closed.
